### ISSUE TITLE
Collisions

### ISSUE THREAD

**Issue by TheJustExper** [squeek502/bunnyhop-webgl#1]
Where are the collisions actually detected and responsed too? I'm trying to make the player / camera pass through a mesh however i collide with it so i can't. I'm not too sure of where this is actually held, could you shine some light on this.

**Comment by squeek502** [comment]
The easiest way to make a mesh non-solid would be to skip over it in this loop:

https://github.com/squeek502/bunnyhop-webgl/blob/220c6c9248fda8aa9c3fedaff742842052874c2e/src/Collisions.js#L160-L167

i.e. adding this to the top of the loop and implementing a function called `isNonSolid` that returns true when a non-solid mesh is passed to it:

```js
if ( isNonSolid(meshes[i]) ) {
  continue;
}
```

This TODO would also be related, as it would provide a more general way of handling what-collides-with-what (`predicate` would be a function that returns true for things that should collide, false for things that shouldn't):

https://github.com/squeek502/bunnyhop-webgl/blob/220c6c9248fda8aa9c3fedaff742842052874c2e/src/Collisions.js#L157-L158

**Comment by TheJustExper** [comment]
Ah now i see, thank you that actually helps, i'm starting to learn 3d stuff by reading and adjusting what's already been made. I thought that Babylon randomly had a physics engine running already but realised that's not the case. Thank you for that.

**Comment by squeek502** [comment]
The collisions here needed to be custom since the Quake engine has some physics quirks that I wanted to replicate (see [this blog post for example](https://www.ryanliptak.com/blog/rampsliding-quake-engine-quirk/)).

There might be better examples to learn from if you're not interested in the Quake-engine-style movement physics; this was my first time using Babylon so I'm sure I'm doing things in a non-standard/weird way (most people probably don't implement their own collision system).

**Comment by TheJustExper** [comment]
To be honest with you i'm adjusting this to sort of get it in the direction of conventional surfing that is on games such as counter strike source and csgo. I needed to stop some collisions as I would make these "zones" meaning once you're inside them make the players timer either start or stop.

I am trying to do everything that source / quake does however so I will look into adding more things.

**Comment by TheJustExper** [comment]
What i'm doing at the moment looks like this. https://i.imgur.com/Qw4yf5V.png

**Comment by squeek502** [comment]
Ah, cool. Surfing should work, but I haven't tested it too much. I know surfing typically uses really high sv_airaccelerate so you'll probably want to adjust this as well:

https://github.com/squeek502/bunnyhop-webgl/blob/220c6c9248fda8aa9c3fedaff742842052874c2e/src/Game.js#L39

**Comment by TheJustExper** [comment]
I have the surfing setup however there is a little problem, going behind slanted ramps results in the error: clipVelocity with 0 backoff. I would try and debug and see why however I actually am not good at physics nor maths at all and am trying to build myself up by trial and error.

**Comment by TheJustExper** [comment]
https://i.imgur.com/hPWo76g.gifv

**Comment by squeek502** [comment]
Interesting, haven't tested that case. I'm guessing it's because of this:

https://github.com/squeek502/bunnyhop-webgl/blob/220c6c9248fda8aa9c3fedaff742842052874c2e/src/Player.js#L58-L63

**Comment by TheJustExper** [comment]
Nope doesn't seem to change anything, not sure what it could be

**Comment by squeek502** [comment]
Not sure what you tried, but the fix there would be a port of the CheckStuck code from Quake/HL:

- [HL1's code](https://github.com/ValveSoftware/halflife/blob/c7240b965743a53a29491dd49320c88eecf6257b/pm_shared/pm_shared.c#L1630-L1748)
- [Quake1's code](https://github.com/id-Software/Quake/blob/bf4ac424ce754894ac8f1dae6a3981954bc9852d/QW/client/pmove.c#L735-L769)

Quake's version is much simpler but might be less complete (most of the existing code is based on HL1's implementations).

**Comment by squeek502** [comment]
Looked into it more and realized that my hunch was wrong. The error should be fixed by https://github.com/squeek502/bunnyhop-webgl/commit/4048c3639c39c76d1013b6f1374eb7e07809e97d but it still feels like something is off. I've split it into its own issue: https://github.com/squeek502/bunnyhop-webgl/issues/2
